// import {createSlice} from '@reduxjs/toolkit';
// // import {localimag} from '../../Provider/Localimage';

// const initialState = {
//   homeData: {
//     featured: [
//       {
//         id: 0,
//         image: localimag.icon_computer,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1000',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 1,
//         image: localimag.icon_purse,
//         title: 'Men Regular Fit Collar Casual Shirt',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 2,
//         image: localimag.icon_computer,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 3,
//         image: localimag.icon_purse,
//         title: 'Men Regular Fit Collar Casual Shirt',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 4,
//         image: localimag.icon_computer,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 5,
//         image: localimag.icon_purse,
//         title: 'Men Regular Fit Collar Casual Shirt',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 6,
//         image: localimag.icon_purse,
//         title: 'Men Regular Fit Collar Casual Shirt',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//     ],
//     stories: [
//       {
//         id: 0,
//         image: require('../../Icons/Images/image_card_1.jpg'),
//         title: 'Success Story : How I tripled my sales',
//         time: '1 hour ago',
//       },
//       {
//         id: 1,
//         image: require('../../Icons/Images/image_card_1.jpg'),
//         title: 'Success Story : How I tripled my sales',
//         time: '1 hour ago',
//       },
//       {
//         id: 2,
//         image: require('../../Icons/Images/image_card_1.jpg'),
//         title: 'Success Story : How I tripled my sales',
//         time: '1 hour ago',
//       },
//     ],
//     inspired: [
//       {
//         id: 0,
//         image: localimag.image_shoes,
//         title: 'Trendy Running Shoes For Men',
//         currency: '1500',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 1,
//         image: localimag.image_watch,
//         title: 'Fundamentals Analog Watch',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 2,
//         image: localimag.image_wardrobe,
//         title: 'Outfit classy RB GT',
//         currency: '1650',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 3,
//         image: localimag.image_bench,
//         title: 'Bench Fume 21',
//         currency: '1650',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 4,
//         image: localimag.image_wardrobe,
//         title: 'Sample T-shirt Fume 21',
//         currency: '25',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 5,
//         image: localimag.image_watch,
//         title: 'Fundamentals Analog Watch',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 6,
//         image: localimag.image_shoes,
//         title: 'Trendy Running Shoes For Men',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//     ],
//     popular: [
//       {
//         id: 0,
//         image: localimag.image_redIphone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 1,
//         image: localimag.image_blackCamera,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 2,
//         image: localimag.image_redIphone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 3,
//         image: localimag.image_blackCamera,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 4,
//         image: localimag.image_redIphone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 5,
//         image: localimag.image_blackCamera,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 6,
//         image: localimag.image_redIphone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//     ],
//     urgent: [
//       {
//         id: 0,
//         image: localimag.image_red,
//         title: 'SWISS BEAUTY Lipstic S6-212 Berry ',
//         currency: '1500',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 1,
//         image: localimag.image_camera,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 2,
//         image: localimag.image_red,
//         title: 'SWISS BEAUTY Lipstic S6-212 Berry ',
//         currency: '1500',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 3,
//         image: localimag.image_camera,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 4,
//         image: localimag.image_red,
//         title: 'SWISS BEAUTY Lipstic S6-212 Berry ',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 5,
//         image: localimag.image_camera,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 6,
//         image: localimag.image_red,
//         title: 'SWISS BEAUTY Lipstic S6-212 Berry ',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//     ],
//     nearBy: [
//       {
//         id: 0,
//         image: localimag.image__brown_headPhone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 1,
//         image: localimag.image_white_headphone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 2,
//         image: localimag.image__brown_headPhone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 3,
//         image: localimag.image_white_headphone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 4,
//         image: localimag.image__brown_headPhone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 5,
//         image: localimag.image_white_headphone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 6,
//         image: localimag.image__brown_headPhone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//     ],
//     listing: [
//       {
//         id: 0,
//         image: localimag.image_bench,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 1,
//         image: localimag.image_white_headphone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 2,
//         image: localimag.image__brown_headPhone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 3,
//         image: localimag.image_white_headphone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//     ],
//     listing_1: [
//       {
//         id: 0,
//         image: localimag.image_bench,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 1,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 1,
//         image: localimag.image_christmas,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//       {
//         id: 2,
//         image: localimag.image_christmas,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 2,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 3,
//         image: localimag.image_white_headphone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: true,
//       },
//       {
//         id: 4,
//         image: localimag.image_white_headphone,
//         title: 'Lenovo I7 11h Gen GTX 1650',
//         currency: '1500',
//         proStatus: 0,
//         location: 'Paris',
//         save: false,
//         discount: false,
//       },
//     ],

//     categories: [
//       {
//         id: 0,
//         category: 'Women',
//         icon: localimag.icon_women_dress,
//         save: false,
//       },
//       {
//         id: 1,
//         category: 'Men',
//         icon: localimag.icon_men_dress,
//         save: false,
//       },
//       {
//         id: 2,
//         category: 'Cars',
//         icon: localimag.icon_car,
//         save: false,
//       },
//       {
//         id: 3,
//         category: 'Electronics',
//         icon: localimag.icon_elect,
//         save: false,
//       },
//     ],
//   },
// };

// const homeSlice = createSlice({
//   name: 'homeData',
//   initialState,
//   reducers: {
//     likeDislike: (state, action) => {
//       const {arrayName, index} = action.payload;
//       if (state.homeData[arrayName] && state.homeData[arrayName][index]) {
//         state.homeData[arrayName][index].save =
//           !state.homeData[arrayName][index].save;
//       }
//     },
//   },
// });

// export const {likeDislike} = homeSlice.actions;

// export default homeSlice.reducer;
